language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"

# command to run tests, e.g. python setup.py test
script: python -c 'import datashape; datashape.test(exit=True)'

notifications:
  email: false
  flowdock: b08b3ba4fb86fa48121e90b5f67ccb75
  on_success: "change"
  on_failure: "always"

