language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install pytest"

# command to run tests, e.g. python setup.py test
script: py.test --doctest-modules --verbose --pyargs datashape

notifications:
  email: false
  flowdock: b08b3ba4fb86fa48121e90b5f67ccb75
  on_success: "change"
  on_failure: "always"

