package:
    name: datashape
    version: "0.2.2"

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}
    script:
      - cd $RECIPE_DIR
      - $PYTHON setup.py install

requirements:
    build:
      - python

    run:
      - python
      - numpy
      - multipledispatch
      - nose

about:
    home: http://datashape.pydata.org
    license: BSD
