source:
    git_url: git@github.com:ContinuumIO/datashape.git

package:
    name: datashape
    version: "0.4.1"

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}
    script:
      - $PYTHON setup.py install

requirements:
    build:
      - python

    run:
      - python
      - numpy
      - multipledispatch
      - dateutil

test:
  requires:
  - pytest
  commands:
  - python -c 'import datashape; datashape.test()'


about:
    home: http://datashape.pydata.org
    license: BSD
