package:
    name: datashape
    version: "0.4.2"

build:
    script:
      - cd $RECIPE_DIR/..
      - $PYTHON setup.py install

requirements:
    build:
      - python

    run:
      - python
      - numpy
      - multipledispatch
      - dateutil

test:
  requires:
  - pytest
  commands:
  - python -c "import datashape; datashape.test()"


about:
    home: http://datashape.pydata.org
    license: BSD
