package:
  name: datashape
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: ../

requirements:
  build:
    - python

  run:
    - python
    - numpy >=1.7
    - multipledispatch >=0.4.7
    - python-dateutil

test:
  requires:
    - pytest
  imports:
    - datashape
  commands:
    - py.test --doctest-modules --pyargs datashape


about:
  home: http://datashape.pydata.org
  license: BSD
