package:
  name: datashape
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: ../

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - multipledispatch
    - dateutil

test:
  requires:
  - pytest
  commands:
  - py.test --doctest-modules --pyargs datashape


about:
  home: http://datashape.pydata.org
  license: BSD
